export const lyricsPages = [
  "Teri zulfa ne aaisa jadu kareya",
  "Mere dil te rang tera chadeya",
  "Ki ye man wich dassana me chaunda ya",
  "Tahi war war tere rahi aauna ya",

  "Akhle tu mere wal ek vaar",
  "Ruleya phirda mera ghar war",
  "Kal mile si tu menu chehra vadh",
  "Hun har ek kudich me",
  "Tainu labda fira",

  "Tainu labda fira",
  "Kitthe gum gayi tu",
  "Tainu labda fira",
  "Mera jee nahi lagda",
  "Mera jee nahi lagda",
  "Tainu labda fira",
  "Tainu labda fira",

  "Labda fira",
  "Labda fira",
  "Labda fira",
  "Tainu labda fira",
  "Labda fira",
  "Kitthe dur gayi tu",
  "Tainu labda fira",

  "Akhiyanu tere lod he ve sanjha",
  "Aaja tu mere kol he ve",
  "Lang kinne saal he",
  "Dil wich e sawal he",
  "Kyun nahi tu mere naal he",
  "Kyun nahi tu mere naal he",

  "Mere dil ne na manni kadi haar",
  "Hoke marde nu honge kinne saal",
  "Aida munda kidde ghumda nahi",
  "Par tere sher diya sadka te",

  "Tainu labda fira",
  "Tainu labda fira",
  "Kitthe gum gayi tu",
  "Tainu labda fira",
  "Mera jee nahi lagda",
  "Mera jee nahi lagda",
  "Tainu labda fira",
  "Tainu labda fira",

  "Labda fira",
  "Labda fira",
  "Labda fira",
  "Tainu labda fira",
  "Labda fira",
  "Kitthe dur gayi tu",
  "Tainu labda fira",
];
